export const URLS = {
	SAP_INDENTS_URL: process.env.SAP_BASE_URL + "/YEBANESLLAPI_SRV/HeaderEBANSet",
	SAP_VENDORS_URL: process.env.SAP_BASE_URL + "/YVENDORGETAPI_SRV/YVENDORSet",
	SAP_PO_URL: process.env.SAP_BASE_URL + "/YPOPORTAL_POST_SRV/HeaderSet",
}
